# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440c082b344760506f69d787392f4e3c118d074b7476f0ae690e2a5f9c619c5274044f139bf56396338f8b62a45ae2e24633941b6bdaf734fbfd89ea36106f4f

test:
  secret_key_base: 95eef3ee787f66a2f761049870abfa36cfb9b082f8918233d3cf19e11f6cc19a7016189e987e98ab7c61f322934789594d9e49c9df18a9f020e1c83ba163df56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
