Location.delete_all
guadalupe = Location.create("title" => "Guadalupe Island", "accomodation" => "Liveaboard", "nearest_airport" => "Tijuana (TIJ)", "photomap_id" => "http://www.allaboutbaja.com/images/bajamaps/xbajamapfull.gif")
pulmo = Location.create("title" => "Cabo Pulmo", "accomodation" => "Cabo Pulmo", "nearest_airport" => "La Paz (LAP), San Jose del Cabo (SJD)", "photomap_id" => "http://www.allaboutbaja.com/images/bajamaps/xbajamapfull.gif")
magbay = Location.create("title" => "Bahia Magdalena", "accomodation" => "Puerto San Carlos", "nearest_airport" => "La Paz (LAP), San Jose del Cabo (SJD)", "photomap_id" => "http://www.allaboutbaja.com/images/bajamaps/xbajamapfull.gif")
loscabos = Location.create("title" => "Los Cabos", "accomodation" => "Los Cabos", "nearest_airport" => "San Jose del Cabo (SJD)", "photomap_id" => "http://www.allaboutbaja.com/images/bajamaps/xbajamapfull.gif")
revi = Location.create("title" => "Revillagigedo Islands", "accomodation" => "Liveaboard", "nearest_airport" => "San Jose del Cabo (SJD)", "photomap_id" => "http://www.allaboutbaja.com/images/bajamaps/xbajamapfull.gif")
chinchorro = Location.create("title" => "Chinchorro Atoll", "accomodation" => "Xcalak", "nearest_airport" => "Chetumal (CTM), Cancun (CUN)", "photomap_id" => "http://www.mayanbeachgarden.com/Images/local-mapLG.gif")
xcalak = Location.create("title" => "Xcalak", "accomodation" => "Xcalak", "nearest_airport" => "Cancun (CUN)", "photomap_id" => "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/RivieraMayaMap.svg/1452px-RivieraMayaMap.svg.png")
tulum = Location.create("title" => "Tulum", "accomodation" => "Tulum", "nearest_airport" => "Cancun (CUN)", "photomap_id" => "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/RivieraMayaMap.svg/1452px-RivieraMayaMap.svg.png")
playa = Location.create("title" => "Playa del Carmen", "accomodation" => "Playa del Carmen", "nearest_airport" => "Cancun (CUN)", "photomap_id" => "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/RivieraMayaMap.svg/1452px-RivieraMayaMap.svg.png")
cancun = Location.create("title" => "Cancun", "accomodation" => "Cancun", "nearest_airport" => "Cancun (CUN)", "photomap_id" => "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/RivieraMayaMap.svg/1452px-RivieraMayaMap.svg.png")

Operator.delete_all
sea = Operator.create("title" => "Seascape", "owner" => "Fernando Aguilar", "contact_url" => "http://www.seaescapeliveaboard.com/content/contact")
pul = Operator.create("title" => "Cabo Pulmo Divers", "owner" => "Antonio Romero", "contact_url" => "http://www.cabopulmo.com/contact-us-cabo-pulmo-mexico/")
mag = Operator.create("title" => "Magbay Sports", "owner" => "Gabino Mendevil", "contact_url" => "https://www.facebook.com/magbay.sport?fref=ts")
pel = Operator.create("title" => "Pelagic Life", "owner" => "Eduardo Martinez", "contact_url" => "http://www.pelagiclife.org/#!about/cxq5")
man = Operator.create("title" => "Manta Divers", "owner" => "Francisco Mendez", "contact_url" => "http://www.caboscuba.com/en/contact-us")
xtc = Operator.create("title" => "XTC Divers", "owner" => "Javier Salas", "contact_url" => "https://www.xtcdivecenter.com/RESERVATIONS.html")
pep = Operator.create("title" => "Pepe Dive Center", "owner" => "Pepe Esteban", "contact_url" => "http://www.pepedivecenter.com/")
pha = Operator.create("title" => "Phantom Divers", "owner" => "Jorge Loria", "contact_url" => "http://www.phantomdivers.com/en/home")
sob = Operator.create("title" => "Solo Buceo", "owner" => "Rodrigo Friscione", "contact_url" => "http://solobuceo.com/contact.php")
sol = Operator.create("title" => "Sol Mar V", "owner" => "Erick Higuera", "contact_url" => "http://solmarv.com/contact.html")

Month.delete_all
jan = Month.create("title" => "January")
feb = Month.create("title" => "February")
mar = Month.create("title" => "March")
apr = Month.create("title" => "April")
may = Month.create("title" => "May")
jun = Month.create("title" => "June")
jul = Month.create("title" => "July")
aug = Month.create("title" => "August")
sep = Month.create("title" => "September")
oct = Month.create("title" => "October")
nov = Month.create("title" => "November")
dec = Month.create("title" => "December")

Trip.delete_all
gws = Trip.create("title" => "Great White Sharks", "location_id" => guadalupe.id, "description" => "Great White Sharks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sea.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_e9d994f85e0148ed9761c9a2b4bf6f26.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
sj = Trip.create("title" => "Schooling Jacks", "location_id" => pulmo.id, "description" => "Schooling Jacks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => pul.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_25e081f1a4464a65a083aad283e8ce75.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
bms = Trip.create("title" => "Blue & Mako Sharks", "location_id" => magbay.id, "description" => "Blue & Mako Sharks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => mag.id, "probability" => "70", "photo_url" => "http://static.wixstatic.com/media/103f43_834eab1c87904d5e82e4e1b01ee547ae.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
smb = Trip.create("title" => "Striped Marlin Baitball", "location_id" => magbay.id, "description" => "Striped Marlin Baitball is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => pel.id, "probability" => "20", "photo_url" => "http://static.wixstatic.com/media/103f43_f93604bc35194378abf69067e19166a3.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
gwh = Trip.create("title" => "Grey Whales", "location_id" => magbay.id, "description" => "Grey Whales is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => mag.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_51ce263731d74c9790c1ba236a7180b0.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
shh = Trip.create("title" => "Schooling Hammerheads", "location_id" => loscabos.id, "description" => "Schooling Hammerheads is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => man.id, "probability" => "60", "photo_url" => "http://static.wixstatic.com/media/103f43_e395c876fb78462e8420c014a889332c.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
gmp = Trip.create("title" => "Giant Mantas Pacific", "location_id" => revi.id, "description" => "Giant Mantas Pacific is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sol.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_521b5522c4f44d5391eb786e72e0a0eb.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
ss = Trip.create("title" => "Schooling Sharks", "location_id" => revi.id, "description" => "Schooling Sharks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sol.id, "probability" => "60", "photo_url" => "http://static.wixstatic.com/media/103f43_f351d393c9d7456495bd5653e8feea8e.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
swc = Trip.create("title" => "Salt Water Crocodiles", "location_id" => chinchorro.id, "description" => "Salt Water Crocodiles is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => xtc.id, "probability" => "85", "photo_url" => "http://static.wixstatic.com/media/103f43_93c2ba384dbc467c804ebd8b97cf5d51.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
tar = Trip.create("title" => "Tarphoon", "location_id" => xcalak.id, "description" => "Tarphoon is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => xtc.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_635544f88b334feab439152e70fa9119.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
cad = Trip.create("title" => "Cave Diving", "location_id" => tulum.id, "description" => "Cave Diving is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => pep.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_9b1d1070abf04d22b6303531abbeec45.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
bsp = Trip.create("title" => "Bull Sharks", "location_id" => playa.id, "description" => "Bull Sharks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => pha.id, "probability" => "80", "photo_url" => "http://static.wixstatic.com/media/103f43_e7868cd30b604990becb615e7e648a45.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
ws = Trip.create("title" => "Whale Sharks", "location_id" => cancun.id, "description" => "Whale Sharks is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sob.id, "probability" => "90", "photo_url" => "http://static.wixstatic.com/media/103f43_89c75f081da44468bb7a508a50368192.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
sbb = Trip.create("title" => "Sailfish Baitball", "location_id" => cancun.id, "description" => "Sailfish Baitball is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sob.id, "probability" => "70", "photo_url" => "http://static.wixstatic.com/media/103f43_8f6260f7a8ca4ffe9e7885575aa9173c.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")
gmc = Trip.create("title" => "Giant Mantas Carribean", "location_id" => cancun.id, "description" => "Giant Mantas Carribean is argubly the best location in the world to view Great White Sharks. Large congregation of male and female sharks go to Guadalupe Island to feed and some scientist debate white else drives them to this single location. To view the Great Whites most people board a live aboard in Ensenada (a port 1 hour south of Tijuana) and make a full day crossing to arrive to this deserted island. On the island infamous prison beach (a small bay located in the north east side of the island) sharks usually show up within a couple of hours of throwing chum in the water. It is quite commmon to see multiple sharks at the same time and if you are looking to seriously photograph great white sharks Guadalupe offers unparralel water visibility and shark congregation. Liveaboards usually run 5 day expeditions with 3 days of diving. ", "operator_id" => sob.id, "probability" => "70", "photo_url" => "http://static.wixstatic.com/media/103f43_9fdddde6d63d420a87877138bb0527c2.jpg_srz_p_180_120_75_22_0.50_1.20_0.00_jpg_srz")

Season.delete_all
Season.create("trip_id" => gws.id, "month_id" => aug.id)
Season.create("trip_id" => gws.id, "month_id" => sep.id)
Season.create("trip_id" => gws.id, "month_id" => oct.id)
Season.create("trip_id" => gws.id, "month_id" => nov.id)
Season.create("trip_id" => sj.id, "month_id" => jul.id)
Season.create("trip_id" => sj.id, "month_id" => aug.id)
Season.create("trip_id" => sj.id, "month_id" => sep.id)
Season.create("trip_id" => sj.id, "month_id" => oct.id)
Season.create("trip_id" => sj.id, "month_id" => nov.id)
Season.create("trip_id" => bms.id, "month_id" => may.id)
Season.create("trip_id" => bms.id, "month_id" => jun.id)
Season.create("trip_id" => bms.id, "month_id" => jul.id)
Season.create("trip_id" => bms.id, "month_id" => aug.id)
Season.create("trip_id" => bms.id, "month_id" => sep.id)
Season.create("trip_id" => bms.id, "month_id" => oct.id)
Season.create("trip_id" => bms.id, "month_id" => nov.id)
Season.create("trip_id" => bms.id, "month_id" => dec.id)
Season.create("trip_id" => smb.id, "month_id" => nov.id)
Season.create("trip_id" => smb.id, "month_id" => dec.id)
Season.create("trip_id" => gwh.id, "month_id" => jan.id)
Season.create("trip_id" => gwh.id, "month_id" => feb.id)
Season.create("trip_id" => gwh.id, "month_id" => mar.id)
Season.create("trip_id" => shh.id, "month_id" => jul.id)
Season.create("trip_id" => shh.id, "month_id" => aug.id)
Season.create("trip_id" => shh.id, "month_id" => sep.id)
Season.create("trip_id" => shh.id, "month_id" => oct.id)
Season.create("trip_id" => gmp.id, "month_id" => nov.id)
Season.create("trip_id" => gmp.id, "month_id" => dec.id)
Season.create("trip_id" => gmp.id, "month_id" => jan.id)
Season.create("trip_id" => gmp.id, "month_id" => feb.id)
Season.create("trip_id" => gmp.id, "month_id" => mar.id)
Season.create("trip_id" => gmp.id, "month_id" => apr.id)
Season.create("trip_id" => gmp.id, "month_id" => may.id)
Season.create("trip_id" => ss.id, "month_id" => may.id)
Season.create("trip_id" => ss.id, "month_id" => jun.id)
Season.create("trip_id" => swc.id, "month_id" => jan.id)
Season.create("trip_id" => swc.id, "month_id" => feb.id)
Season.create("trip_id" => swc.id, "month_id" => mar.id)
Season.create("trip_id" => swc.id, "month_id" => apr.id)
Season.create("trip_id" => swc.id, "month_id" => may.id)
Season.create("trip_id" => swc.id, "month_id" => jun.id)
Season.create("trip_id" => swc.id, "month_id" => jul.id)
Season.create("trip_id" => swc.id, "month_id" => aug.id)
Season.create("trip_id" => swc.id, "month_id" => sep.id)
Season.create("trip_id" => swc.id, "month_id" => oct.id)
Season.create("trip_id" => swc.id, "month_id" => nov.id)
Season.create("trip_id" => swc.id, "month_id" => dec.id)
Season.create("trip_id" => tar.id, "month_id" => jan.id)
Season.create("trip_id" => tar.id, "month_id" => feb.id)
Season.create("trip_id" => tar.id, "month_id" => mar.id)
Season.create("trip_id" => tar.id, "month_id" => apr.id)
Season.create("trip_id" => tar.id, "month_id" => may.id)
Season.create("trip_id" => tar.id, "month_id" => jun.id)
Season.create("trip_id" => tar.id, "month_id" => jul.id)
Season.create("trip_id" => tar.id, "month_id" => aug.id)
Season.create("trip_id" => tar.id, "month_id" => sep.id)
Season.create("trip_id" => tar.id, "month_id" => oct.id)
Season.create("trip_id" => tar.id, "month_id" => nov.id)
Season.create("trip_id" => tar.id, "month_id" => dec.id)
Season.create("trip_id" => cad.id, "month_id" => jan.id)
Season.create("trip_id" => cad.id, "month_id" => feb.id)
Season.create("trip_id" => cad.id, "month_id" => mar.id)
Season.create("trip_id" => cad.id, "month_id" => apr.id)
Season.create("trip_id" => cad.id, "month_id" => may.id)
Season.create("trip_id" => cad.id, "month_id" => jun.id)
Season.create("trip_id" => cad.id, "month_id" => jul.id)
Season.create("trip_id" => cad.id, "month_id" => aug.id)
Season.create("trip_id" => cad.id, "month_id" => sep.id)
Season.create("trip_id" => cad.id, "month_id" => oct.id)
Season.create("trip_id" => cad.id, "month_id" => nov.id)
Season.create("trip_id" => cad.id, "month_id" => dec.id)
Season.create("trip_id" => bsp.id, "month_id" => nov.id)
Season.create("trip_id" => bsp.id, "month_id" => dec.id)
Season.create("trip_id" => bsp.id, "month_id" => jan.id)
Season.create("trip_id" => bsp.id, "month_id" => feb.id)
Season.create("trip_id" => bsp.id, "month_id" => mar.id)
Season.create("trip_id" => ws.id, "month_id" => jun.id)
Season.create("trip_id" => ws.id, "month_id" => jul.id)
Season.create("trip_id" => ws.id, "month_id" => aug.id)
Season.create("trip_id" => sbb.id, "month_id" => jan.id)
Season.create("trip_id" => sbb.id, "month_id" => feb.id)
Season.create("trip_id" => sbb.id, "month_id" => mar.id)
Season.create("trip_id" => gmc.id, "month_id" => sep.id)
Season.create("trip_id" => gmc.id, "month_id" => oct.id)

User.delete_all
jero = User.create("username" => "jero", "password" => "pelagiclife", "name" => "Jero Prieto")
lalo = User.create("username" => "lalo", "password" => "cecilia", "name" => "Eduardo Martinez")
ana = User.create("username" => "ana", "password" => "germany", "name" => "Ana Lagos")

Review.delete_all
Review.create("user_id" => jero.id, "trip_id" => bms.id, "rating" => 5, "content" => "I love blue sharks!")
Review.create("user_id" => jero.id, "trip_id" => gws.id, "rating" => 1, "content" => "Great encounter with LARGE SHARKS!")
Review.create("user_id" => ana.id, "trip_id" => gws.id, "rating" => 2, "content" => "I really enjoyed the accomodations")
Review.create("user_id" => ana.id, "trip_id" => bms.id , "rating" => 4, "content" => "I love going to Bahia Magdalena!")
Review.create("user_id" => lalo.id, "trip_id" => gws.id, "rating" => 5, "content" => "Cageless diving with great white sharks is not allowed")